name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pipenv and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv --upgrade-strategy=only-if-needed
        pipenv install
    - name: Run test
      run : |
        pipenv run test ./ACoL
        pipenv run test ./UNet
        pipenv run test ./ArcFace

